version: '3'
services:
  app:
    container_name: apptest
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/user/src/app
  mongo:
    container_name: appmongotest
    image: mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
